name = "GridSim"
uuid = "eb5af87e-af5a-4058-ac7e-47b2baa55413"
version = "0.1.0"
authors = ["Boyko Neov <boikoneov@gmail.com>"]

[deps]
CommonSolve = "38540f10-b2f7-11e9-35d8-d573e4eb0ff2"
Observables = "510215fc-4207-5dde-b226-833fc4488ee2"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"

[compat]
CommonSolve = "0.2.7"
Observables = "0.5.5"
OrdinaryDiffEq = "7.0.1"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
